name: smart_task_manager
description: Build a app to management request HTTP
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  intl: ^0.20.2
  # --- json_annotation MOVIDO AQUÍ ---
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  # json_annotation: ^4.9.0 # <-- Eliminado de aquí
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
