name: smart_task_manager
description: Build a app to management request HTTP
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  # --- json_annotation MOVIDO AQUÍ ---
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  # json_annotation: ^4.9.0 # <-- Eliminado de aquí
  json_serializable: ^6.11.1
  mocktail: ^1.0.3
  hive_test: ^1.0.0
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tarea.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/tarea.png"
  min_sdk_android: 21
 
flutter_native_splash:
  image: assets/icon/tarea.png
  color: "#FFFFFF"
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icon/tarea.png
    color: "#FFFFFF"
